/*
 * generated by Xtext 2.21.0
 */
package org.xtext.example.domainmodel.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.domainmodel.DomainmodelRuntimeModule;
import org.xtext.example.domainmodel.DomainmodelStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DomainmodelIdeSetup extends DomainmodelStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DomainmodelRuntimeModule(), new DomainmodelIdeModule()));
	}
	
}
