/*
 * generated by Xtext 2.21.0
 */
package org.xtext.example.domainmodel.ide;


/**
 * Use this class to register ide components.
 */
public class DomainmodelIdeModule extends AbstractDomainmodelIdeModule {
}
