/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.domainmodel.domainmodel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.domainmodel.domainmodel.Declaration#getTrainingstring <em>Trainingstring</em>}</li>
 *   <li>{@link org.xtext.example.domainmodel.domainmodel.Declaration#getReference <em>Reference</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.domainmodel.domainmodel.DomainmodelPackage#getDeclaration()
 * @model
 * @generated
 */
public interface Declaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Trainingstring</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Trainingstring</em>' attribute.
   * @see #setTrainingstring(String)
   * @see org.xtext.example.domainmodel.domainmodel.DomainmodelPackage#getDeclaration_Trainingstring()
   * @model
   * @generated
   */
  String getTrainingstring();

  /**
   * Sets the value of the '{@link org.xtext.example.domainmodel.domainmodel.Declaration#getTrainingstring <em>Trainingstring</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Trainingstring</em>' attribute.
   * @see #getTrainingstring()
   * @generated
   */
  void setTrainingstring(String value);

  /**
   * Returns the value of the '<em><b>Reference</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reference</em>' containment reference.
   * @see #setReference(Reference)
   * @see org.xtext.example.domainmodel.domainmodel.DomainmodelPackage#getDeclaration_Reference()
   * @model containment="true"
   * @generated
   */
  Reference getReference();

  /**
   * Sets the value of the '{@link org.xtext.example.domainmodel.domainmodel.Declaration#getReference <em>Reference</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reference</em>' containment reference.
   * @see #getReference()
   * @generated
   */
  void setReference(Reference value);

} // Declaration
