/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.domainmodel.domainmodel;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.domainmodel.domainmodel.DomainmodelFactory
 * @model kind="package"
 * @generated
 */
public interface DomainmodelPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "domainmodel";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/domainmodel/Domainmodel";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "domainmodel";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DomainmodelPackage eINSTANCE = org.xtext.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.domainmodel.domainmodel.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.domainmodel.domainmodel.impl.ModelImpl
   * @see org.xtext.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Agent</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__AGENT = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.domainmodel.domainmodel.impl.AgentImpl <em>Agent</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.domainmodel.domainmodel.impl.AgentImpl
   * @see org.xtext.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getAgent()
   * @generated
   */
  int AGENT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Agent</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.domainmodel.domainmodel.impl.IntentImpl <em>Intent</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.domainmodel.domainmodel.impl.IntentImpl
   * @see org.xtext.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getIntent()
   * @generated
   */
  int INTENT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTENT__NAME = AGENT__NAME;

  /**
   * The feature id for the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTENT__SUPER_TYPE = AGENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Is Follow Up</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTENT__IS_FOLLOW_UP = AGENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Question</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTENT__QUESTION = AGENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Training</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTENT__TRAINING = AGENT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Intent</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTENT_FEATURE_COUNT = AGENT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.example.domainmodel.domainmodel.impl.IsFollowUpImpl <em>Is Follow Up</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.domainmodel.domainmodel.impl.IsFollowUpImpl
   * @see org.xtext.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getIsFollowUp()
   * @generated
   */
  int IS_FOLLOW_UP = 3;

  /**
   * The feature id for the '<em><b>Intent</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IS_FOLLOW_UP__INTENT = 0;

  /**
   * The number of structural features of the '<em>Is Follow Up</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IS_FOLLOW_UP_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.domainmodel.domainmodel.impl.EntityImpl <em>Entity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.domainmodel.domainmodel.impl.EntityImpl
   * @see org.xtext.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getEntity()
   * @generated
   */
  int ENTITY = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__NAME = AGENT__NAME;

  /**
   * The feature id for the '<em><b>Example</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__EXAMPLE = AGENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Entity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FEATURE_COUNT = AGENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.domainmodel.domainmodel.impl.QuestionImpl <em>Question</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.domainmodel.domainmodel.impl.QuestionImpl
   * @see org.xtext.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getQuestion()
   * @generated
   */
  int QUESTION = 5;

  /**
   * The feature id for the '<em><b>Question Entity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION__QUESTION_ENTITY = 0;

  /**
   * The feature id for the '<em><b>Prompt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION__PROMPT = 1;

  /**
   * The number of structural features of the '<em>Question</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.domainmodel.domainmodel.impl.QuestionEntityImpl <em>Question Entity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.domainmodel.domainmodel.impl.QuestionEntityImpl
   * @see org.xtext.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getQuestionEntity()
   * @generated
   */
  int QUESTION_ENTITY = 6;

  /**
   * The feature id for the '<em><b>With Entity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION_ENTITY__WITH_ENTITY = 0;

  /**
   * The number of structural features of the '<em>Question Entity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION_ENTITY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.domainmodel.domainmodel.impl.TrainingImpl <em>Training</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.domainmodel.domainmodel.impl.TrainingImpl
   * @see org.xtext.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getTraining()
   * @generated
   */
  int TRAINING = 7;

  /**
   * The feature id for the '<em><b>Trainingref</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRAINING__TRAININGREF = 0;

  /**
   * The number of structural features of the '<em>Training</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRAINING_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.domainmodel.domainmodel.impl.TrainingRefImpl <em>Training Ref</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.domainmodel.domainmodel.impl.TrainingRefImpl
   * @see org.xtext.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getTrainingRef()
   * @generated
   */
  int TRAINING_REF = 8;

  /**
   * The feature id for the '<em><b>Phrase</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRAINING_REF__PHRASE = 0;

  /**
   * The feature id for the '<em><b>Declaration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRAINING_REF__DECLARATION = 1;

  /**
   * The number of structural features of the '<em>Training Ref</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRAINING_REF_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.domainmodel.domainmodel.impl.DeclarationImpl <em>Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.domainmodel.domainmodel.impl.DeclarationImpl
   * @see org.xtext.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getDeclaration()
   * @generated
   */
  int DECLARATION = 9;

  /**
   * The feature id for the '<em><b>Trainingstring</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION__TRAININGSTRING = 0;

  /**
   * The feature id for the '<em><b>Reference</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION__REFERENCE = 1;

  /**
   * The number of structural features of the '<em>Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.domainmodel.domainmodel.impl.EntityExampleImpl <em>Entity Example</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.domainmodel.domainmodel.impl.EntityExampleImpl
   * @see org.xtext.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getEntityExample()
   * @generated
   */
  int ENTITY_EXAMPLE = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_EXAMPLE__NAME = 0;

  /**
   * The number of structural features of the '<em>Entity Example</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_EXAMPLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.domainmodel.domainmodel.impl.SysvariableImpl <em>Sysvariable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.domainmodel.domainmodel.impl.SysvariableImpl
   * @see org.xtext.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getSysvariable()
   * @generated
   */
  int SYSVARIABLE = 11;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSVARIABLE__VALUE = 0;

  /**
   * The number of structural features of the '<em>Sysvariable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSVARIABLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.domainmodel.domainmodel.impl.ReferenceImpl <em>Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.domainmodel.domainmodel.impl.ReferenceImpl
   * @see org.xtext.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getReference()
   * @generated
   */
  int REFERENCE = 12;

  /**
   * The feature id for the '<em><b>Entity</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE__ENTITY = 0;

  /**
   * The feature id for the '<em><b>Sysvar</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE__SYSVAR = 1;

  /**
   * The number of structural features of the '<em>Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.example.domainmodel.domainmodel.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.domainmodel.domainmodel.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.domainmodel.domainmodel.Model#getAgent <em>Agent</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Agent</em>'.
   * @see org.xtext.example.domainmodel.domainmodel.Model#getAgent()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Agent();

  /**
   * Returns the meta object for class '{@link org.xtext.example.domainmodel.domainmodel.Agent <em>Agent</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Agent</em>'.
   * @see org.xtext.example.domainmodel.domainmodel.Agent
   * @generated
   */
  EClass getAgent();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.domainmodel.domainmodel.Agent#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.domainmodel.domainmodel.Agent#getName()
   * @see #getAgent()
   * @generated
   */
  EAttribute getAgent_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.domainmodel.domainmodel.Intent <em>Intent</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Intent</em>'.
   * @see org.xtext.example.domainmodel.domainmodel.Intent
   * @generated
   */
  EClass getIntent();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.domainmodel.domainmodel.Intent#getSuperType <em>Super Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Super Type</em>'.
   * @see org.xtext.example.domainmodel.domainmodel.Intent#getSuperType()
   * @see #getIntent()
   * @generated
   */
  EReference getIntent_SuperType();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.domainmodel.domainmodel.Intent#getIsFollowUp <em>Is Follow Up</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Is Follow Up</em>'.
   * @see org.xtext.example.domainmodel.domainmodel.Intent#getIsFollowUp()
   * @see #getIntent()
   * @generated
   */
  EReference getIntent_IsFollowUp();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.domainmodel.domainmodel.Intent#getQuestion <em>Question</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Question</em>'.
   * @see org.xtext.example.domainmodel.domainmodel.Intent#getQuestion()
   * @see #getIntent()
   * @generated
   */
  EReference getIntent_Question();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.domainmodel.domainmodel.Intent#getTraining <em>Training</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Training</em>'.
   * @see org.xtext.example.domainmodel.domainmodel.Intent#getTraining()
   * @see #getIntent()
   * @generated
   */
  EReference getIntent_Training();

  /**
   * Returns the meta object for class '{@link org.xtext.example.domainmodel.domainmodel.IsFollowUp <em>Is Follow Up</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Is Follow Up</em>'.
   * @see org.xtext.example.domainmodel.domainmodel.IsFollowUp
   * @generated
   */
  EClass getIsFollowUp();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.domainmodel.domainmodel.IsFollowUp#getIntent <em>Intent</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Intent</em>'.
   * @see org.xtext.example.domainmodel.domainmodel.IsFollowUp#getIntent()
   * @see #getIsFollowUp()
   * @generated
   */
  EReference getIsFollowUp_Intent();

  /**
   * Returns the meta object for class '{@link org.xtext.example.domainmodel.domainmodel.Entity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entity</em>'.
   * @see org.xtext.example.domainmodel.domainmodel.Entity
   * @generated
   */
  EClass getEntity();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.domainmodel.domainmodel.Entity#getExample <em>Example</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Example</em>'.
   * @see org.xtext.example.domainmodel.domainmodel.Entity#getExample()
   * @see #getEntity()
   * @generated
   */
  EReference getEntity_Example();

  /**
   * Returns the meta object for class '{@link org.xtext.example.domainmodel.domainmodel.Question <em>Question</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Question</em>'.
   * @see org.xtext.example.domainmodel.domainmodel.Question
   * @generated
   */
  EClass getQuestion();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.domainmodel.domainmodel.Question#getQuestionEntity <em>Question Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Question Entity</em>'.
   * @see org.xtext.example.domainmodel.domainmodel.Question#getQuestionEntity()
   * @see #getQuestion()
   * @generated
   */
  EReference getQuestion_QuestionEntity();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.domainmodel.domainmodel.Question#getPrompt <em>Prompt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Prompt</em>'.
   * @see org.xtext.example.domainmodel.domainmodel.Question#getPrompt()
   * @see #getQuestion()
   * @generated
   */
  EAttribute getQuestion_Prompt();

  /**
   * Returns the meta object for class '{@link org.xtext.example.domainmodel.domainmodel.QuestionEntity <em>Question Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Question Entity</em>'.
   * @see org.xtext.example.domainmodel.domainmodel.QuestionEntity
   * @generated
   */
  EClass getQuestionEntity();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.domainmodel.domainmodel.QuestionEntity#getWithEntity <em>With Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>With Entity</em>'.
   * @see org.xtext.example.domainmodel.domainmodel.QuestionEntity#getWithEntity()
   * @see #getQuestionEntity()
   * @generated
   */
  EReference getQuestionEntity_WithEntity();

  /**
   * Returns the meta object for class '{@link org.xtext.example.domainmodel.domainmodel.Training <em>Training</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Training</em>'.
   * @see org.xtext.example.domainmodel.domainmodel.Training
   * @generated
   */
  EClass getTraining();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.domainmodel.domainmodel.Training#getTrainingref <em>Trainingref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Trainingref</em>'.
   * @see org.xtext.example.domainmodel.domainmodel.Training#getTrainingref()
   * @see #getTraining()
   * @generated
   */
  EReference getTraining_Trainingref();

  /**
   * Returns the meta object for class '{@link org.xtext.example.domainmodel.domainmodel.TrainingRef <em>Training Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Training Ref</em>'.
   * @see org.xtext.example.domainmodel.domainmodel.TrainingRef
   * @generated
   */
  EClass getTrainingRef();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.domainmodel.domainmodel.TrainingRef#getPhrase <em>Phrase</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Phrase</em>'.
   * @see org.xtext.example.domainmodel.domainmodel.TrainingRef#getPhrase()
   * @see #getTrainingRef()
   * @generated
   */
  EAttribute getTrainingRef_Phrase();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.domainmodel.domainmodel.TrainingRef#getDeclaration <em>Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Declaration</em>'.
   * @see org.xtext.example.domainmodel.domainmodel.TrainingRef#getDeclaration()
   * @see #getTrainingRef()
   * @generated
   */
  EReference getTrainingRef_Declaration();

  /**
   * Returns the meta object for class '{@link org.xtext.example.domainmodel.domainmodel.Declaration <em>Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Declaration</em>'.
   * @see org.xtext.example.domainmodel.domainmodel.Declaration
   * @generated
   */
  EClass getDeclaration();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.domainmodel.domainmodel.Declaration#getTrainingstring <em>Trainingstring</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Trainingstring</em>'.
   * @see org.xtext.example.domainmodel.domainmodel.Declaration#getTrainingstring()
   * @see #getDeclaration()
   * @generated
   */
  EAttribute getDeclaration_Trainingstring();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.domainmodel.domainmodel.Declaration#getReference <em>Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Reference</em>'.
   * @see org.xtext.example.domainmodel.domainmodel.Declaration#getReference()
   * @see #getDeclaration()
   * @generated
   */
  EReference getDeclaration_Reference();

  /**
   * Returns the meta object for class '{@link org.xtext.example.domainmodel.domainmodel.EntityExample <em>Entity Example</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entity Example</em>'.
   * @see org.xtext.example.domainmodel.domainmodel.EntityExample
   * @generated
   */
  EClass getEntityExample();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.domainmodel.domainmodel.EntityExample#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.domainmodel.domainmodel.EntityExample#getName()
   * @see #getEntityExample()
   * @generated
   */
  EAttribute getEntityExample_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.domainmodel.domainmodel.Sysvariable <em>Sysvariable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sysvariable</em>'.
   * @see org.xtext.example.domainmodel.domainmodel.Sysvariable
   * @generated
   */
  EClass getSysvariable();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.domainmodel.domainmodel.Sysvariable#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.domainmodel.domainmodel.Sysvariable#getValue()
   * @see #getSysvariable()
   * @generated
   */
  EAttribute getSysvariable_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.domainmodel.domainmodel.Reference <em>Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Reference</em>'.
   * @see org.xtext.example.domainmodel.domainmodel.Reference
   * @generated
   */
  EClass getReference();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.domainmodel.domainmodel.Reference#getEntity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Entity</em>'.
   * @see org.xtext.example.domainmodel.domainmodel.Reference#getEntity()
   * @see #getReference()
   * @generated
   */
  EReference getReference_Entity();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.domainmodel.domainmodel.Reference#getSysvar <em>Sysvar</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Sysvar</em>'.
   * @see org.xtext.example.domainmodel.domainmodel.Reference#getSysvar()
   * @see #getReference()
   * @generated
   */
  EReference getReference_Sysvar();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DomainmodelFactory getDomainmodelFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.domainmodel.domainmodel.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.domainmodel.domainmodel.impl.ModelImpl
     * @see org.xtext.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Agent</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__AGENT = eINSTANCE.getModel_Agent();

    /**
     * The meta object literal for the '{@link org.xtext.example.domainmodel.domainmodel.impl.AgentImpl <em>Agent</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.domainmodel.domainmodel.impl.AgentImpl
     * @see org.xtext.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getAgent()
     * @generated
     */
    EClass AGENT = eINSTANCE.getAgent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AGENT__NAME = eINSTANCE.getAgent_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.domainmodel.domainmodel.impl.IntentImpl <em>Intent</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.domainmodel.domainmodel.impl.IntentImpl
     * @see org.xtext.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getIntent()
     * @generated
     */
    EClass INTENT = eINSTANCE.getIntent();

    /**
     * The meta object literal for the '<em><b>Super Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTENT__SUPER_TYPE = eINSTANCE.getIntent_SuperType();

    /**
     * The meta object literal for the '<em><b>Is Follow Up</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTENT__IS_FOLLOW_UP = eINSTANCE.getIntent_IsFollowUp();

    /**
     * The meta object literal for the '<em><b>Question</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTENT__QUESTION = eINSTANCE.getIntent_Question();

    /**
     * The meta object literal for the '<em><b>Training</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTENT__TRAINING = eINSTANCE.getIntent_Training();

    /**
     * The meta object literal for the '{@link org.xtext.example.domainmodel.domainmodel.impl.IsFollowUpImpl <em>Is Follow Up</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.domainmodel.domainmodel.impl.IsFollowUpImpl
     * @see org.xtext.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getIsFollowUp()
     * @generated
     */
    EClass IS_FOLLOW_UP = eINSTANCE.getIsFollowUp();

    /**
     * The meta object literal for the '<em><b>Intent</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IS_FOLLOW_UP__INTENT = eINSTANCE.getIsFollowUp_Intent();

    /**
     * The meta object literal for the '{@link org.xtext.example.domainmodel.domainmodel.impl.EntityImpl <em>Entity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.domainmodel.domainmodel.impl.EntityImpl
     * @see org.xtext.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getEntity()
     * @generated
     */
    EClass ENTITY = eINSTANCE.getEntity();

    /**
     * The meta object literal for the '<em><b>Example</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY__EXAMPLE = eINSTANCE.getEntity_Example();

    /**
     * The meta object literal for the '{@link org.xtext.example.domainmodel.domainmodel.impl.QuestionImpl <em>Question</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.domainmodel.domainmodel.impl.QuestionImpl
     * @see org.xtext.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getQuestion()
     * @generated
     */
    EClass QUESTION = eINSTANCE.getQuestion();

    /**
     * The meta object literal for the '<em><b>Question Entity</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUESTION__QUESTION_ENTITY = eINSTANCE.getQuestion_QuestionEntity();

    /**
     * The meta object literal for the '<em><b>Prompt</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute QUESTION__PROMPT = eINSTANCE.getQuestion_Prompt();

    /**
     * The meta object literal for the '{@link org.xtext.example.domainmodel.domainmodel.impl.QuestionEntityImpl <em>Question Entity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.domainmodel.domainmodel.impl.QuestionEntityImpl
     * @see org.xtext.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getQuestionEntity()
     * @generated
     */
    EClass QUESTION_ENTITY = eINSTANCE.getQuestionEntity();

    /**
     * The meta object literal for the '<em><b>With Entity</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUESTION_ENTITY__WITH_ENTITY = eINSTANCE.getQuestionEntity_WithEntity();

    /**
     * The meta object literal for the '{@link org.xtext.example.domainmodel.domainmodel.impl.TrainingImpl <em>Training</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.domainmodel.domainmodel.impl.TrainingImpl
     * @see org.xtext.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getTraining()
     * @generated
     */
    EClass TRAINING = eINSTANCE.getTraining();

    /**
     * The meta object literal for the '<em><b>Trainingref</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRAINING__TRAININGREF = eINSTANCE.getTraining_Trainingref();

    /**
     * The meta object literal for the '{@link org.xtext.example.domainmodel.domainmodel.impl.TrainingRefImpl <em>Training Ref</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.domainmodel.domainmodel.impl.TrainingRefImpl
     * @see org.xtext.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getTrainingRef()
     * @generated
     */
    EClass TRAINING_REF = eINSTANCE.getTrainingRef();

    /**
     * The meta object literal for the '<em><b>Phrase</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRAINING_REF__PHRASE = eINSTANCE.getTrainingRef_Phrase();

    /**
     * The meta object literal for the '<em><b>Declaration</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRAINING_REF__DECLARATION = eINSTANCE.getTrainingRef_Declaration();

    /**
     * The meta object literal for the '{@link org.xtext.example.domainmodel.domainmodel.impl.DeclarationImpl <em>Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.domainmodel.domainmodel.impl.DeclarationImpl
     * @see org.xtext.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getDeclaration()
     * @generated
     */
    EClass DECLARATION = eINSTANCE.getDeclaration();

    /**
     * The meta object literal for the '<em><b>Trainingstring</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECLARATION__TRAININGSTRING = eINSTANCE.getDeclaration_Trainingstring();

    /**
     * The meta object literal for the '<em><b>Reference</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DECLARATION__REFERENCE = eINSTANCE.getDeclaration_Reference();

    /**
     * The meta object literal for the '{@link org.xtext.example.domainmodel.domainmodel.impl.EntityExampleImpl <em>Entity Example</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.domainmodel.domainmodel.impl.EntityExampleImpl
     * @see org.xtext.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getEntityExample()
     * @generated
     */
    EClass ENTITY_EXAMPLE = eINSTANCE.getEntityExample();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTITY_EXAMPLE__NAME = eINSTANCE.getEntityExample_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.domainmodel.domainmodel.impl.SysvariableImpl <em>Sysvariable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.domainmodel.domainmodel.impl.SysvariableImpl
     * @see org.xtext.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getSysvariable()
     * @generated
     */
    EClass SYSVARIABLE = eINSTANCE.getSysvariable();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SYSVARIABLE__VALUE = eINSTANCE.getSysvariable_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.domainmodel.domainmodel.impl.ReferenceImpl <em>Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.domainmodel.domainmodel.impl.ReferenceImpl
     * @see org.xtext.example.domainmodel.domainmodel.impl.DomainmodelPackageImpl#getReference()
     * @generated
     */
    EClass REFERENCE = eINSTANCE.getReference();

    /**
     * The meta object literal for the '<em><b>Entity</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REFERENCE__ENTITY = eINSTANCE.getReference_Entity();

    /**
     * The meta object literal for the '<em><b>Sysvar</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REFERENCE__SYSVAR = eINSTANCE.getReference_Sysvar();

  }

} //DomainmodelPackage
