/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.domainmodel.domainmodel;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Intent</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.domainmodel.domainmodel.Intent#getSuperType <em>Super Type</em>}</li>
 *   <li>{@link org.xtext.example.domainmodel.domainmodel.Intent#getIsFollowUp <em>Is Follow Up</em>}</li>
 *   <li>{@link org.xtext.example.domainmodel.domainmodel.Intent#getQuestion <em>Question</em>}</li>
 *   <li>{@link org.xtext.example.domainmodel.domainmodel.Intent#getTraining <em>Training</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.domainmodel.domainmodel.DomainmodelPackage#getIntent()
 * @model
 * @generated
 */
public interface Intent extends Agent
{
  /**
   * Returns the value of the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Super Type</em>' reference.
   * @see #setSuperType(Intent)
   * @see org.xtext.example.domainmodel.domainmodel.DomainmodelPackage#getIntent_SuperType()
   * @model
   * @generated
   */
  Intent getSuperType();

  /**
   * Sets the value of the '{@link org.xtext.example.domainmodel.domainmodel.Intent#getSuperType <em>Super Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Super Type</em>' reference.
   * @see #getSuperType()
   * @generated
   */
  void setSuperType(Intent value);

  /**
   * Returns the value of the '<em><b>Is Follow Up</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Follow Up</em>' containment reference.
   * @see #setIsFollowUp(IsFollowUp)
   * @see org.xtext.example.domainmodel.domainmodel.DomainmodelPackage#getIntent_IsFollowUp()
   * @model containment="true"
   * @generated
   */
  IsFollowUp getIsFollowUp();

  /**
   * Sets the value of the '{@link org.xtext.example.domainmodel.domainmodel.Intent#getIsFollowUp <em>Is Follow Up</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Follow Up</em>' containment reference.
   * @see #getIsFollowUp()
   * @generated
   */
  void setIsFollowUp(IsFollowUp value);

  /**
   * Returns the value of the '<em><b>Question</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.domainmodel.domainmodel.Question}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Question</em>' containment reference list.
   * @see org.xtext.example.domainmodel.domainmodel.DomainmodelPackage#getIntent_Question()
   * @model containment="true"
   * @generated
   */
  EList<Question> getQuestion();

  /**
   * Returns the value of the '<em><b>Training</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Training</em>' containment reference.
   * @see #setTraining(Training)
   * @see org.xtext.example.domainmodel.domainmodel.DomainmodelPackage#getIntent_Training()
   * @model containment="true"
   * @generated
   */
  Training getTraining();

  /**
   * Sets the value of the '{@link org.xtext.example.domainmodel.domainmodel.Intent#getTraining <em>Training</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Training</em>' containment reference.
   * @see #getTraining()
   * @generated
   */
  void setTraining(Training value);

} // Intent
