/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.domainmodel.domainmodel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Question</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.domainmodel.domainmodel.Question#getQuestionEntity <em>Question Entity</em>}</li>
 *   <li>{@link org.xtext.example.domainmodel.domainmodel.Question#getPrompt <em>Prompt</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.domainmodel.domainmodel.DomainmodelPackage#getQuestion()
 * @model
 * @generated
 */
public interface Question extends EObject
{
  /**
   * Returns the value of the '<em><b>Question Entity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Question Entity</em>' containment reference.
   * @see #setQuestionEntity(QuestionEntity)
   * @see org.xtext.example.domainmodel.domainmodel.DomainmodelPackage#getQuestion_QuestionEntity()
   * @model containment="true"
   * @generated
   */
  QuestionEntity getQuestionEntity();

  /**
   * Sets the value of the '{@link org.xtext.example.domainmodel.domainmodel.Question#getQuestionEntity <em>Question Entity</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Question Entity</em>' containment reference.
   * @see #getQuestionEntity()
   * @generated
   */
  void setQuestionEntity(QuestionEntity value);

  /**
   * Returns the value of the '<em><b>Prompt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prompt</em>' attribute.
   * @see #setPrompt(String)
   * @see org.xtext.example.domainmodel.domainmodel.DomainmodelPackage#getQuestion_Prompt()
   * @model
   * @generated
   */
  String getPrompt();

  /**
   * Sets the value of the '{@link org.xtext.example.domainmodel.domainmodel.Question#getPrompt <em>Prompt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prompt</em>' attribute.
   * @see #getPrompt()
   * @generated
   */
  void setPrompt(String value);

} // Question
