/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.domainmodel.domainmodel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Training Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.domainmodel.domainmodel.TrainingRef#getPhrase <em>Phrase</em>}</li>
 *   <li>{@link org.xtext.example.domainmodel.domainmodel.TrainingRef#getDeclaration <em>Declaration</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.domainmodel.domainmodel.DomainmodelPackage#getTrainingRef()
 * @model
 * @generated
 */
public interface TrainingRef extends EObject
{
  /**
   * Returns the value of the '<em><b>Phrase</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Phrase</em>' attribute.
   * @see #setPhrase(String)
   * @see org.xtext.example.domainmodel.domainmodel.DomainmodelPackage#getTrainingRef_Phrase()
   * @model
   * @generated
   */
  String getPhrase();

  /**
   * Sets the value of the '{@link org.xtext.example.domainmodel.domainmodel.TrainingRef#getPhrase <em>Phrase</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Phrase</em>' attribute.
   * @see #getPhrase()
   * @generated
   */
  void setPhrase(String value);

  /**
   * Returns the value of the '<em><b>Declaration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declaration</em>' containment reference.
   * @see #setDeclaration(Declaration)
   * @see org.xtext.example.domainmodel.domainmodel.DomainmodelPackage#getTrainingRef_Declaration()
   * @model containment="true"
   * @generated
   */
  Declaration getDeclaration();

  /**
   * Sets the value of the '{@link org.xtext.example.domainmodel.domainmodel.TrainingRef#getDeclaration <em>Declaration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Declaration</em>' containment reference.
   * @see #getDeclaration()
   * @generated
   */
  void setDeclaration(Declaration value);

} // TrainingRef
