/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.domainmodel.domainmodel;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Training</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.domainmodel.domainmodel.Training#getTrainingref <em>Trainingref</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.domainmodel.domainmodel.DomainmodelPackage#getTraining()
 * @model
 * @generated
 */
public interface Training extends EObject
{
  /**
   * Returns the value of the '<em><b>Trainingref</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.domainmodel.domainmodel.TrainingRef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Trainingref</em>' containment reference list.
   * @see org.xtext.example.domainmodel.domainmodel.DomainmodelPackage#getTraining_Trainingref()
   * @model containment="true"
   * @generated
   */
  EList<TrainingRef> getTrainingref();

} // Training
