/*
 * generated by Xtext 2.21.0
 */
package org.xtext.example.domainmodel;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DomainmodelRuntimeModule extends AbstractDomainmodelRuntimeModule {
}
