/*
 * generated by Xtext 2.21.0
 */
package org.xtext.example.domainmodel.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.domainmodel.ui.internal.DomainmodelActivator;

public class DomainmodelUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DomainmodelActivator.getInstance().getInjector("org.xtext.example.domainmodel.Domainmodel");
	}

}
